services:
  # mysql:
  #   image: mysql:latest
  #   container_name: dev-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root!@34
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: devuser
  #     MYSQL_PASSWORD: 1234
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app-network
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  # mongodb:
  #   image: mongo:latest
  #   container_name: dev-mongodb
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network
  #   volumes:
  #     - mongo-data:/data/db

  backend:
    build:
      context: ./backend/boot-demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://dev-mysql:3306/mydatabase
    #   SPRING_DATASOURCE_USERNAME: devuser
    #   SPRING_DATASOURCE_PASSWORD: 1234
    #   SPRING_MONGODB_URI: mongodb://dev-mongodb:27017/mydatabase
    # depends_on:
    #   - mysql
    #   - mongodb

  frontend:
    build:
      context: ./frontend/react-demo/oauth-jwt-demo
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

# volumes:
#   mysql-data:
#   mongo-data:


networks:
  app-network:
    driver: bridge
